### ISSUE TITLE
function get_encoded_text(container, xpath) seems to be dysfunctional

### ISSUE THREAD

**Issue by QuEFIST** [jkitchin/scopus#16]
Dear Prof. Kitchin,
Thanks for your Git.
I used the example you posted:
from scopus.scopus_author import ScopusAuthor
au = ScopusAuthor(7004212771)
print([a.name for a in au.get_coauthors()])

It worked for me, then suddenly it is broken, the information is like this:
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

It looks like the function, get_encoded_text, can not parse the correct number of elements.
Hope you noted this.
Thanks

**Comment by QuEFIST** [comment]
looks like it is because my api quota is exceeded.

**Comment by Michael-E-Rose** [comment]
That is a good occasion: I always wanted to propose to run pre-checks to catch the numerous [errors](https://api.elsevier.com/documentation/AuthorRetrievalAPI.wadl) the server may send.  It should not be too difficult to parse the error message and handle them differently.  The challenge is to avoid to write this for each class separately.

**Comment by Michael-E-Rose** [comment]
Not directly fixed, because there was no bug/error, but can be closed due to 5e40ac8f073f57461000f02cfb832268165213ff
