### ISSUE TITLE
Why no references in ScopusAbstract() class?

### ISSUE THREAD

**Issue by Michael-E-Rose** [jkitchin/scopus#8]
The `ScopusAbstract()` class from [`scopus_api.py`](https://github.com/jkitchin/scopus/blob/master/scopus/scopus_api.py#L138) explicitly downloads the "META_ABS" view.  This does not include references of this article.  Is there a reason why they should be excluded?  If so, whats is the next best way to obtain the references of an article?

The general view (i.e. removing `'?view=META_ABS'`) would include the references and still provide the same information currently used.

**Comment by jkitchin** [comment]
Probably no reason. Maybe it was faster at one time. It seems like it would make sense to make it an option though.

**Comment by Michael-E-Rose** [comment]
Cool! I am happy to implement this.

But let's think this through: There should also be a property or a corresponding property in this class to list the references - otherwise the new information is worthless. But this property will only work when the user has used the apparently optional parameter to include references. We could let the user know that they have to set the option, but I don't deem this good style.

Instead, why not making a transition phase? It will be the standard in ~3 months from now (without option, otherwise the property/method will break), and until then it is an option whose default is to not load the references (like now). But when the default mode is use, a FutureWarning notifys the user about the upcoming change and suggest him what to do for a smooth transition.

What do you think about this?

**Comment by jkitchin** [comment]
in the init function you could provide a new argument like view='META_ABS'. Then in https://github.com/jkitchin/scopus/blob/master/scopus/scopus_api.py#L138 modify it to:

EID) 
if view:
    url += + '?view=' + view

wouldn't this work? The default would stay the same, but you could easily change the view.

**Comment by Michael-E-Rose** [comment]
Yes, this would work.

But what I meant is a notification for the use, when he wants to access the references based on a method (that I will provide as well), and then the references are not there.

**Comment by Michael-E-Rose** [comment]
Fixed with 16aa978f5b31595d52b913cf9c605c8d63cf8141
